# count crawls prior to 2019-01-06
SELECT (count(distinct(?crawl)) as ?count)
 WHERE {
   values ?verb { <http://www.w3.org/ns/prov#generatedAtTime> } .
   #?s <http://www.w3.org/ns/prov#generatedAtTime> ?date .
   ?s ?verb ?date .
   # OPTIONAL { ?s <http://www.w3.org/ns/prov#wasGeneratedBy> ?crawl . }
   ?s <http://www.w3.org/ns/prov#wasGeneratedBy> ?crawl . 
   FILTER (?date < "2019-01-06T10:20:13Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>)
}
LIMIT 25
